services:
    - docker

language: go

go:
  -  1.9.x

git:
  depth: 300

branches:
  only:
    - master

matrix:
  include:

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: linux
      dist: trusty
      sudo: required
      env: RUN_UI_TESTS=1 SKIP_NOMAD_TESTS=1
    - os: osx
      osx_image: xcode9.1


cache:
  directories:
    - ui/node_modules

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sudo bash ./scripts/travis-mac.sh ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo bash ./scripts/travis-linux.sh ; fi

install:
  - make bootstrap

script:
  - sudo -E "PATH=$PATH" make travis
